;/*FB_PKG_DELIM*/

__d("CometMarketplaceComponentLoggingContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u={metadata:null},c=s.createContext(u);l.default=c}),98);
__d("ProductTagPostClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1744228"),s=o("FalcoLoggerInternal").create("product_tag_post_click",e),u=s;l.default=u}),98);
__d("CometProductTagLoggingUtils",["ProductTagPostClickFalcoEvent","requireDeferred"],(function(t,n,r,o,a,i,l){"use strict";var e=r("requireDeferred")("CommerceStorefrontImpressionFalcoEvent").__setRef("CometProductTagLoggingUtils"),s=r("requireDeferred")("CommerceTabFeedImpressionFalcoEvent").__setRef("CometProductTagLoggingUtils"),u="product_tag_on_",c=function(t,n,o,a,i,l){r("ProductTagPostClickFalcoEvent").log(function(){return{ad_id:t,component:n,funnel_id:o,marketplace_surface:a,post_id:i,referral_code:l}})},d=function(n,r,o,a,i,l,c,d){var t,m=_(i,o),p=m.analyticsPage,f=m.isPageFeed,g=m.isTabFeed,h=m.isTimeline,y=m.surface,C=u+((t=y!=null?y:i)!=null?t:"")+"_"+n,b=r!=null;if(p!=null){if(g)s.onReady(function(e){e.log(function(){var e;return{analytics_component:l,analytics_destination_page:a,analytics_feed_type:p==="home_feed"?"newsfeed":"unknown",analytics_module:c,analytics_page:p,content_id:n,legacy_referral_code:C,legacy_surface:(e=y!=null?y:i)!=null?e:"",legacy_ui_component:d,referral_surface:"unknown",shopping_session_id:""}})});else if(f||b&&h){var v={analytics_feed_type:f?"page":"profile",analytics_module:c,analytics_page:p,content_id:n,referral_surface:"unknown",shopping_session_id:""};e.onReady(function(e){e.log(function(){return babelHelpers.extends({},v)})})}}},m=function(t){var e;return t==="AYMTNotificationChannel"?e="aymt_retro_tag_jewel":t==="AYMTEmailChannel"?e="aymt_retro_tag_email":t==="AYMTPageAdminMegaphoneV2Channel"||t==="AYMTPageAdminMegaphoneChannel"?e="aymt_retro_tag_megaphone":t==="AYMTUnknownChannel"&&(e="aymt_unknown_channel"),e},p=function(t,n,r,o){switch(t){case"home_feed":case"posts_feed":return n===1&&r?"product_details":o?"video_fullscreen":"photo_fullscreen";case"video_feed":return"video_fullscreen";default:return"unknown"}},_=function(t,n){var e=null,r=null,o=!1,a=!1,i=!1;switch(t){case"NEWSFEED":e="home_feed",r="newsfeed",o=!0;break;case"PAGE_TIMELINE":a=!0,e="posts_feed",r="pages_feed";break;case"TIMELINE":i=!0,e="posts_feed",r="pages_feed";break;default:t!=null&&t.includes("VIDEO")||n==="video_home"?(e="video_feed",r="video_home",o=!0):t!=null&&t.includes("GROUP")&&(e=null,r="group_mall")}return{analyticsPage:e,isPageFeed:a,isTabFeed:o,isTimeline:i,surface:r!=null?r:n}};l.logProductTagPostClick=c,l.logImpressionEventForNewsFeedAndStorefront=d,l.getAYMTChannelName=m,l.getAnalyticsDestinationPage=p,l.getSurface=_}),98);
__d("CometProductTagReferralCodeContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext(null);l.default=u}),98);
__d("CommerceTabFeedClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1878"),s=o("FalcoLoggerInternal").create("commerce_tab_feed_click",e),u=s;l.default=u}),98);
__d("CommerceTabFeedImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("2315"),s=o("FalcoLoggerInternal").create("commerce_tab_feed_impression",e),u=s;l.default=u}),98);
__d("CommerceAttachmentLoggingUtils",["CommerceTabFeedClickFalcoEvent","CommerceTabFeedImpressionFalcoEvent"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t){var n="unknown";switch(e){case"homepage_stream":case"groups_tab":n="home_feed";break;case"group":n="group_feed";break}var r="unknown";switch(t){case"NEWSFEED":r="newsfeed";break;case"GROUP":r="groups";break}return{analyticsExperience:"tab_feed",analyticsFeedType:r,analyticsPage:n}}function s(e,t){return e?"post":t?"shops_you_follow_stories":"unknown"}function u(e){var t,n,r,o,a,i,l,s;return{analytics_component:(t=e==null?void 0:e.analyticsComponent)!=null?t:"unknown",analytics_feed_type:(n=e==null?void 0:e.analyticsFeedType)!=null?n:"unknown",analytics_module:(r=e==null?void 0:e.analyticsModule)!=null?r:"unknown",analytics_page:(o=e==null?void 0:e.analyticsPage)!=null?o:"unknown",legacy_referral_code:(a=e==null?void 0:e.referralCode)!=null?a:"",module_type:(i=e==null?void 0:e.moduleType)!=null?i:"",navigation_chain:e==null?void 0:e.navigationChain,product_id:(l=e==null?void 0:e.productItemID)!=null?l:"",referral_surface:(s=e==null?void 0:e.analyticsExperience)!=null?s:"unknown",shopping_session_id:""}}function c(e){r("CommerceTabFeedImpressionFalcoEvent").log(function(){return u(e)})}function d(e){r("CommerceTabFeedClickFalcoEvent").log(function(){return u(e)})}function m(e){r("CommerceTabFeedClickFalcoEvent").log(function(){return u(babelHelpers.extends({},e,{analyticsComponent:"message_seller_button"}))})}l.getTabFeedMetadata=e,l.getAttachmentModule=s,l.getBSGAttachmentBasePayload=u,l.logBSGAttachmentImpression=c,l.logBSGAttachmentProductClick=d,l.logBSGAttachmentMessageSellerButtonClick=m}),98);
__d("MarketplaceClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1743922"),s=o("FalcoLoggerInternal").create("marketplace_click",e),u=s;l.default=u}),98);
__d("MarketplaceImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1743925"),s=o("FalcoLoggerInternal").create("marketplace_impression",e),u=s;l.default=u}),98);
__d("XCometCommerceProductItemControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/commerce/products/{?slug}/{listing_id}/",Object.freeze({}),void 0),s=e;l.default=s}),98);